### ISSUE TITLE
Is there wring volumes?

### ISSUE THREAD

**Issue by Dennislampert** [saada/docker-compose-php-mysql#1]
I think that the volumes is wrong.. When I make changes and restart no changes is displayed.. But when I remove  
  volumes:
    - app:/app

My new changes is there.. When i rebuild.
I think that if there is right volumes it should reload wen file changes?
At least when rebuild.

This is fast and nice way to get started! :+1:

**Comment by saada** [comment]
^ the above fix should fix this... thanks for reporting this, @Dennislampert !
closing... :+1:
