### ISSUE TITLE
How do I run phpmyadmin

### ISSUE THREAD

**Issue by developer239** [saada/docker-compose-php-mysql#2]
Hi, thank you for your example. 

How do I run phpmyadmin though? When I added new service to docker-compose.yml I managed to run the phpmyadmin but I could not login.

**Comment by saada** [comment]
I don't know which container you tried to use, but whatever issue you experienced, you should file it to the owner's repo. For example:

https://github.com/phpmyadmin/docker

Here's their sample docker-compose.yml usage for reference:

https://github.com/phpmyadmin/docker/blob/master/docker-compose.yml
